package com.alpha.message.model.email;

import java.util.Date;

public class EmailMessage {

	 /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message.id
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message.email_message_template_id
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    private Long emailMessageTemplateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message.to_address
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    private String toAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message.cc_address
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    private String ccAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message.bcc_address
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    private String bccAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message.priority
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    private Byte priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message.state
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message.immediate
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    private Byte immediate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message.schedule_time
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    private Date scheduleTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message.expired_time
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    private Date expiredTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message.sent_time
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    private Date sentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message.created_time
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message.created_by
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message.DataChange_LastTime
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    private Date datachangeLasttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message.id
     *
     * @return the value of email_message.id
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message.id
     *
     * @param id the value for email_message.id
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message.email_message_template_id
     *
     * @return the value of email_message.email_message_template_id
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    public Long getEmailMessageTemplateId() {
        return emailMessageTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message.email_message_template_id
     *
     * @param emailMessageTemplateId the value for email_message.email_message_template_id
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    public void setEmailMessageTemplateId(Long emailMessageTemplateId) {
        this.emailMessageTemplateId = emailMessageTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message.to_address
     *
     * @return the value of email_message.to_address
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    public String getToAddress() {
        return toAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message.to_address
     *
     * @param toAddress the value for email_message.to_address
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    public void setToAddress(String toAddress) {
        this.toAddress = toAddress == null ? null : toAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message.cc_address
     *
     * @return the value of email_message.cc_address
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    public String getCcAddress() {
        return ccAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message.cc_address
     *
     * @param ccAddress the value for email_message.cc_address
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    public void setCcAddress(String ccAddress) {
        this.ccAddress = ccAddress == null ? null : ccAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message.bcc_address
     *
     * @return the value of email_message.bcc_address
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    public String getBccAddress() {
        return bccAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message.bcc_address
     *
     * @param bccAddress the value for email_message.bcc_address
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    public void setBccAddress(String bccAddress) {
        this.bccAddress = bccAddress == null ? null : bccAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message.priority
     *
     * @return the value of email_message.priority
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    public Byte getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message.priority
     *
     * @param priority the value for email_message.priority
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    public void setPriority(Byte priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message.state
     *
     * @return the value of email_message.state
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message.state
     *
     * @param state the value for email_message.state
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message.immediate
     *
     * @return the value of email_message.immediate
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    public Byte getImmediate() {
        return immediate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message.immediate
     *
     * @param immediate the value for email_message.immediate
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    public void setImmediate(Byte immediate) {
        this.immediate = immediate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message.schedule_time
     *
     * @return the value of email_message.schedule_time
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    public Date getScheduleTime() {
        return scheduleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message.schedule_time
     *
     * @param scheduleTime the value for email_message.schedule_time
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    public void setScheduleTime(Date scheduleTime) {
        this.scheduleTime = scheduleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message.expired_time
     *
     * @return the value of email_message.expired_time
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    public Date getExpiredTime() {
        return expiredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message.expired_time
     *
     * @param expiredTime the value for email_message.expired_time
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    public void setExpiredTime(Date expiredTime) {
        this.expiredTime = expiredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message.sent_time
     *
     * @return the value of email_message.sent_time
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    public Date getSentTime() {
        return sentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message.sent_time
     *
     * @param sentTime the value for email_message.sent_time
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    public void setSentTime(Date sentTime) {
        this.sentTime = sentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message.created_time
     *
     * @return the value of email_message.created_time
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message.created_time
     *
     * @param createdTime the value for email_message.created_time
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message.created_by
     *
     * @return the value of email_message.created_by
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message.created_by
     *
     * @param createdBy the value for email_message.created_by
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message.DataChange_LastTime
     *
     * @return the value of email_message.DataChange_LastTime
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    public Date getDatachangeLasttime() {
        return datachangeLasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message.DataChange_LastTime
     *
     * @param datachangeLasttime the value for email_message.DataChange_LastTime
     *
     * @mbggenerated Wed Aug 12 10:16:04 CST 2015
     */
    public void setDatachangeLasttime(Date datachangeLasttime) {
        this.datachangeLasttime = datachangeLasttime;
    }
}
