
-- --------------------------------------------------------
-- Table :                                  Site  Template
-- --------------------------------------------------------
USE `message`;
-- Base Template
INSERT INTO  site_message_template (id,name,title,content,addition,`type`,state,priority,sender,created_time,created_by,updated_time,updated_by,deleted_time,deleted_by,deleted) VALUES (4000,'base','Base Template','{{content}}',NULL,0,0,1,'Marine Online  Singapore','2018-07-25 11:32:33.000','admin',NULL,NULL,NULL,NULL,0);
-- New Request For Quotation public
INSERT INTO  site_message_template (id,name,title,content,addition,`type`,state,priority,sender,created_time,created_by,updated_time,updated_by,deleted_time,deleted_by,deleted) VALUES(4001,'rfq.new.public','New Request For Quotation','<a href="{{link}}">You have received a new Request For Quotation.Click on message will display Seller&rsquo;s view RFQ (Request For Quotation) page.</a>',NULL,0,0,1,'Marine Online  Singapore','2018-07-25 11:37:56.000','admin',NULL,NULL,NULL,NULL,0);
-- New Request For Quotation private
INSERT INTO  site_message_template (id,name,title,content,addition,`type`,state,priority,sender,created_time,created_by,updated_time,updated_by,deleted_time,deleted_by,deleted) VALUES (4002,'rfq.new.private','New  Request For Quotation','<a href="{{link}}">You have received a new Request For Quotation from {{companyName}}. Click on message will display Seller&rsquo;s view RFQ (Request For Quotation) page.</a>',NULL,0,0,1,'Marine Online  Singapore','2018-07-25 11:37:54.000','admin',NULL,NULL,NULL,NULL,0);
-- Received Quotation
INSERT INTO site_message_template (id,name,title,content,addition,`type`,state,priority,sender,created_time,created_by,updated_time,updated_by,deleted_time,deleted_by,deleted)  VALUES(4003,'quotation.received','New Quotation','<a href="{{link}}">You have received a new Quotation from {{companyName}}. Click on message will display Buyer&rsquo;s view Quotation page.</a>',NULL,0,0,1,'Marine Online  Singapore','2018-07-25 11:37:58.000','admin',NULL,NULL,NULL,NULL,0);
-- Accepted Quotation
INSERT INTO  site_message_template (id,name,title,content,addition,`type`,state,priority,sender,created_time,created_by,updated_time,updated_by,deleted_time,deleted_by,deleted) VALUES(4004,'quotation.accepted','New Quotation','<a href="{{link}}">Your Quotation has been accepted by  {{companyName}}. Click on message will display Seller&rsquo;s view Quotation with status: Appointed under Order Management.</a>',NULL,0,0,1,'Marine Online  Singapore','2018-07-25 11:49:30.000','admin',NULL,NULL,NULL,NULL,0);

-- Order  Handling
INSERT INTO  site_message_template (id,name,title,content,addition,`type`,state,priority,sender,created_time,created_by,updated_time,updated_by,deleted_time,deleted_by,deleted) VALUES (4005,'order.status.handling','Order Handling','<a href="{{link}}">Your Order with Order ID number {{orderId}} is now on Handling. Click on message will display Buyer - Order Management - My Offer - Appointed tab -{{orderId}} with Status: Handling </a>',NULL,0,0,1,'Marine Online  Singapore','2018-07-25 11:32:33.000','admin',NULL,NULL,NULL,NULL,0);
-- Order  Delivery
INSERT INTO  site_message_template (id,name,title,content,addition,`type`,state,priority,sender,created_time,created_by,updated_time,updated_by,deleted_time,deleted_by,deleted) VALUES (4006,'order.status.delivery','Order Delivery','<a href="{{link}}">Your Order with Order ID number {{orderId}} is now on Delivery. Click on message will display Buyer - Order Management - My Offer - Appointed tab -  {{orderId}}  with Status: Delivery</a>',NULL,0,0,1,'Marine Online  Singapore','2018-07-25 11:37:54.000','admin',NULL,NULL,NULL,NULL,0);
-- Order  Delivered
INSERT INTO  site_message_template (id,name,title,content,addition,`type`,state,priority,sender,created_time,created_by,updated_time,updated_by,deleted_time,deleted_by,deleted) VALUES(4007,'order.status.delivered','Order Delivered','<a href="{{link}}"> Your Order with Order ID number {{orderId}} is now Delivered.Click on message will display Buyer - Order Management - My Offer - Appointed tab -{{orderId}} with Status: Delivered</a>',NULL,0,0,1,'Marine Online  Singapore','2018-07-25 11:37:56.000','admin',NULL,NULL,NULL,NULL,0);
-- Order  Partially Paid
INSERT INTO site_message_template (id,name,title,content,addition,`type`,state,priority,sender,created_time,created_by,updated_time,updated_by,deleted_time,deleted_by,deleted)  VALUES(4008,'order.status.partially.paid','Order  Partially Paid','<a href="{{link}}">Your Order with Order ID number {{orderId}} is now Partially Paid. Click on message will display Buyer - Order Management - My Offer - Appointed tab -{{orderId}}  with Status: Partially Paid</a>',NULL,0,0,1,'Marine Online  Singapore','2018-07-25 11:37:58.000','admin',NULL,NULL,NULL,NULL,0);
-- Order  Paid
INSERT INTO  site_message_template (id,name,title,content,addition,`type`,state,priority,sender,created_time,created_by,updated_time,updated_by,deleted_time,deleted_by,deleted) VALUES(4009,'order.status.paid','Order  Paid','<a href="{{link}}">Your Order with Order ID number {{orderId}} is now Paid. Click on message will display Buyer - Order Management - My Offer - Appointed tab -{{orderId}} with Payment Status: Paid</a>',NULL,0,0,1,'Marine Online  Singapore','2018-07-25 11:49:30.000','admin',NULL,NULL,NULL,NULL,0);
-- Order  Completed
INSERT INTO  site_message_template (id,name,title,content,addition,`type`,state,priority,sender,created_time,created_by,updated_time,updated_by,deleted_time,deleted_by,deleted) VALUES (4010,'order.status.completed','Order  Completed','<a href="{{link}}">Your Order with Order ID number {{orderId}} is now Completed. Click on message will display Seller/ MO - Order Management - My Offer - Completed tab - {Order ID Number} with Delivery Status: Delivered and Payment Status: Paid.</a>',NULL,0,0,1,'Marine Online  Singapore','2018-07-25 11:32:33.000','admin',NULL,NULL,NULL,NULL,0);
-- Order  Cancellation by  Buyer
INSERT INTO  site_message_template (id,name,title,content,addition,`type`,state,priority,sender,created_time,created_by,updated_time,updated_by,deleted_time,deleted_by,deleted) VALUES (4011,'order.status.cancel.bybuyer','Order  Cancellation','<a href="{{link}}">{{companyName}} send a cancellation order request for Order ID number {{orderId}}. Click on message will display Seller - Order Management - My Offer - Appointed tab - {{orderId}} with &quot;Cancellation Request&quot; heading and two options: Agree to Cancel and Disagree to Cancel.</a>',NULL,0,0,1,'Marine Online  Singapore','2018-07-25 11:37:54.000','admin',NULL,NULL,NULL,NULL,0);
-- Order  Cancellation  by   Seller
INSERT INTO  site_message_template (id,name,title,content,addition,`type`,state,priority,sender,created_time,created_by,updated_time,updated_by,deleted_time,deleted_by,deleted) VALUES (4012,'order.status.cancel.byseller','Order  Cancellation','<a href="{{link}}">{{companyName}} send a cancellation order request for Order ID number {{orderId}}. Click on message will display Buyer - Order Management - My Enquiry - Appointed tab -  {{orderId}}  with &quot;Cancellation Request&quot; heading and two options: Agree to Cancel and Disagree to Cancel.</a>',NULL,0,0,1,'Marine Online  Singapore','2018-07-25 11:37:54.000','admin',NULL,NULL,NULL,NULL,0);
-- Order  Agrees
INSERT INTO  site_message_template (id,name,title,content,addition,`type`,state,priority,sender,created_time,created_by,updated_time,updated_by,deleted_time,deleted_by,deleted) VALUES(4013,'order.status.agree.bybuyer','Order  Agrees','<a href="{{link}}">{{companyName}} agrees to cancel order for Order ID number {{orderId}}. Click on message will display Seller - Order Management - My Enquiry - Cancelled tab - {{orderId}}  with Status: Cancelled.</a>',NULL,0,0,1,'Marine Online  Singapore','2018-07-25 11:37:56.000','admin',NULL,NULL,NULL,NULL,0);
-- Order  Agrees
INSERT INTO  site_message_template (id,name,title,content,addition,`type`,state,priority,sender,created_time,created_by,updated_time,updated_by,deleted_time,deleted_by,deleted) VALUES(4014,'order.status.agree.byseller','Order  Agrees','<a href="{{link}}">{{companyName}} agrees to cancel order for Order ID number {{orderId}}. Click on message will display Buyer - Order Management - My Enquiry - Cancelled tab - {{orderId}}  with Status: Cancelled.</a>',NULL,0,0,1,'Marine Online  Singapore','2018-07-25 11:37:56.000','admin',NULL,NULL,NULL,NULL,0);
-- Order  Disagrees
INSERT INTO site_message_template (id,name,title,content,addition,`type`,state,priority,sender,created_time,created_by,updated_time,updated_by,deleted_time,deleted_by,deleted)  VALUES(4015,'order.status.disagree.bybuyer','Order  Disagrees','<a href="{{link}}">{{companyName}} disagrees to cancel order for Order ID number {{orderId}}. Click on message will display Seller - Order Management - My Enquiry - Dispute tab -  {{orderId}}  with Status: Dispute.</a>',NULL,0,0,1,'Marine Online  Singapore','2018-07-25 11:37:58.000','admin',NULL,NULL,NULL,NULL,0);
-- Order  Disagrees
INSERT INTO site_message_template (id,name,title,content,addition,`type`,state,priority,sender,created_time,created_by,updated_time,updated_by,deleted_time,deleted_by,deleted)  VALUES(4016,'order.status.disagree.byseller','Order  Disagrees','<a href="{{link}}">{{companyName}} disagrees to cancel order for Order ID number {{orderId}}.  Click on message will display Buyer - Order Management - My Enquiry - Dispute tab -  {{orderId}}  with Status: Dispute.</a>',NULL,0,0,1,'Marine Online  Singapore','2018-07-25 11:37:58.000','admin',NULL,NULL,NULL,NULL,0);
-- Update Quotation
INSERT INTO  site_message_template (id,name,title,content,addition,`type`,state,priority,sender,created_time,created_by,updated_time,updated_by,deleted_time,deleted_by,deleted) VALUES(4017,'order.status.update','Update Quotation','<a href="{{link}}">{{companyName}} updated Quotation for Order ID number {{orderId}}. Click on message will display Buyer - Order Management - My Enquiry - Open tab - {{orderId}}</a>',NULL,0,0,1,'Marine Online  Singapore','2018-07-25 11:49:30.000','admin',NULL,NULL,NULL,NULL,0);
-- Order updload  File  by  Buyer
INSERT INTO  site_message_template (id,name,title,content,addition,`type`,state,priority,sender,created_time,created_by,updated_time,updated_by,deleted_time,deleted_by,deleted) VALUES(4018,'order.status.upload.bybuyer','Order Upload','<a href="{{link}}">{{companyName}} uploaded a file for Order ID number {{orderId}}. Click on message will display  Seller - Order Management - My Enquiry - Open/ Appointed/ Completed/ Cancelled/ Expired/ Dispute/ All tabs - Order ID number  {{orderId}} - View Details - Timeline</a>',NULL,0,0,1,'Marine Online  Singapore','2018-07-25 11:49:30.000','admin',NULL,NULL,NULL,NULL,0);
-- Order updload  File  by  Seller
INSERT INTO  site_message_template (id,name,title,content,addition,`type`,state,priority,sender,created_time,created_by,updated_time,updated_by,deleted_time,deleted_by,deleted) VALUES(4019,'order.status.upload.byseller','Order Upload','<a href="{{link}}">{{companyName}} uploaded a file for Order ID number {{orderId}}. Click on message will display Buyer - Order Management - My Enquiry - Open/ Appointed/ Completed/ Cancelled/ Expired/ Dispute/ All tabs - Order ID number  {{orderId}} - View Details - Timeline</a>',NULL,0,0,1,'Marine Online  Singapore','2018-07-25 11:49:30.000','admin',NULL,NULL,NULL,NULL,0);

-- Job Expiring
INSERT INTO  site_message_template (id,name,title,content,addition,`type`,state,priority,sender,created_time,created_by,updated_time,updated_by,deleted_time,deleted_by,deleted) VALUES(4020,'job.expiring.crewing','Job Expiring','<a href="{{link}}">Job {{jobName}}  is expiring soon. You can extend this if you have not done this previously.Click on message will display Job Detail page of the expiring job.</a>',NULL,0,0,1,'Marine Online  Singapore','2018-07-25 11:49:30.000','admin',NULL,NULL,NULL,NULL,0);
-- Job Expired
INSERT INTO  site_message_template (id,name,title,content,addition,`type`,state,priority,sender,created_time,created_by,updated_time,updated_by,deleted_time,deleted_by,deleted) VALUES(4021,'job.expired.crewing','Job Expired','<a href="{{link}}">Job {{jobName}}  has expired.Click on message will display Job Detail page of the expired job.</a>',NULL,0,0,1,'Marine Online  Singapore','2018-07-25 11:49:30.000','admin',NULL,NULL,NULL,NULL,0);
-- Job  Apply
INSERT INTO  site_message_template (id,name,title,content,addition,`type`,state,priority,sender,created_time,created_by,updated_time,updated_by,deleted_time,deleted_by,deleted) VALUES(4022,'job.apply.crewing','Job Apply','<a href="{{link}}">Applicant {{crewName}}  has applied for {{jobName}}. Click here to view applicant&rsquo;s CV.Click on message will display CV Detail page of the crew.</a>',NULL,0,0,1,'Marine Online  Singapore','2018-07-25 11:49:30.000','admin',NULL,NULL,NULL,NULL,0);

-- New Request For Quotation private chartering
INSERT INTO  site_message_template (id,name,title,content,addition,`type`,state,priority,sender,created_time,created_by,updated_time,updated_by,deleted_time,deleted_by,deleted) VALUES(4023,'rfq.new.private.chartering','New  Request For Quotation','<a href="{{link}}">You have received a new Request For Quotation for {{cargoName}} matching to your {{vesselName}}.Click on message will display RFQ (Request For Quotation) page.</a>',NULL,0,0,1,'Marine Online  Singapore','2018-07-25 11:49:30.000','admin',NULL,NULL,NULL,NULL,0);
-- Received Quotation chartering
INSERT INTO  site_message_template (id,name,title,content,addition,`type`,state,priority,sender,created_time,created_by,updated_time,updated_by,deleted_time,deleted_by,deleted) VALUES(4024,'quotation.new.chartering','New Quotation','<a href="{{link}}"> Cargo owner made a Request for Quotation on unregistered Vessel - {{vesselName}}.</a>',NULL,0,0,1,'Marine Online  Singapore','2018-07-25 11:49:30.000','admin',NULL,NULL,NULL,NULL,0);

-- refused to quote for RFQ
INSERT INTO  site_message_template (id,name,title,content,addition,`type`,state,priority,sender,created_time,created_by,updated_time,updated_by,deleted_time,deleted_by,deleted) VALUES(4025,'rfq.refused.quote','Refused to quote RFQ','{{seller}} refused to quote your Request RFQ Number :{{rfqNo}}, Remarks :{{remarks}}.',NULL,0,0,1,'Marine Online  Singapore','2018-07-25 11:49:30.000','admin',NULL,NULL,NULL,NULL,0);

